code changes required with logging system ,javadoc comments and added…
suchidp/BillingApiAssignment pull request #4
Opened 2022-11-17 13:10 UTC by suchidp

code changes required with logging system ,javadoc comments .
and  In date ,time,total,count getting errors so not added service method

2022-11-18 05:06 UTC, vikaramm requested changes

2022-11-18 05:06 UTC, vikaramm commented on pom.xml
> +            <groupId>org.springframework.boot</groupId>
do we need web dependency ?

2022-11-18 05:06 UTC, vikaramm commented on src/main/java/com/billingapi/controller/InvoiceController.java
> +     * @throws InvoiceNotFoundException  If an Invoice of specific Id is not found
This method doesn't throw any exception ..correct the method comment.

2022-11-18 05:06 UTC, vikaramm commented on src/main/java/com/billingapi/controller/request/InvoiceRequest.java
>      @Digits(integer=3, fraction=2)
ineteger=2  ..because deiscount can not be gerater than 99

2022-11-18 05:06 UTC, vikaramm commented on src/main/java/com/billingapi/controller/request/InvoiceRequest.java
> +    @Min(value = 0, message = "Quantity has to be non negative ")
add @Max (value = 99999999)

2022-11-18 05:06 UTC, vikaramm commented on src/main/java/com/billingapi/controller/request/InvoiceRequest.java
> +    private BigDecimal total;
@Digit (ineteger = 8 , fraction=2 )

2022-11-18 05:06 UTC, vikaramm commented on src/main/resources/log4j2.properties
> +appender.db.type = JDBC
please provide explaination, why we need db  appender.

2022-11-18 05:38 UTC, suchidp commented on src/main/resources/log4j2.properties
> +appender.db.type = JDBC
I thought db appender will create log event in logfile.log ,but it is use to generate  logging events into  database .That was not the requirement of current project.So I am removing it.

2022-11-18 07:19 UTC, vikaramm requested changes

2022-11-18 07:19 UTC, vikaramm commented on src/main/java/com/billingapi/controller/InvoiceController.java
>          if (invoice == null) {
if you can implement something ..
 return invoiceService.findById(invoiceId).orElseThrow(
        () -> new ResponseStatusException(HttpStatus.NOT_FOUND,
            "Invpice id " + invoiceId+ " was not found"));

2022-11-22 12:24 UTC, vikaramm requested changes

2022-11-22 12:24 UTC, vikaramm commented on src/main/java/com/billingapi/controller/request/InvoiceRequest.java
> +    @Digits(integer=2, fraction=2,message = "Discount must be less than 100")
don't add message , Lets use spring default .. Applicable to all other places

2022-11-22 12:24 UTC, vikaramm commented on src/main/java/com/billingapi/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<Object>("Please change your Method type", HttpStatus.NOT_FOUND);
use new ExceptionResponse(ex.getMessage(), HttpStatus.Method_Not_Allowed); object to return applicable to other plces also.

2022-11-22 12:24 UTC, vikaramm commented on src/main/java/com/billingapi/exception/GlobalExceptionHandler.java
> +
Also handle MethodArguementTypeMismatchException and BindException

2022-11-22 12:24 UTC, vikaramm commented on src/main/java/com/billingapi/exception/GlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleMissingPathVariable(MissingPathVariableException ex, HttpHeaders headers, HttpStatus status, WebRequest request) {
This may not required. Please remove.

2022-11-22 12:24 UTC, vikaramm commented on src/main/java/com/billingapi/exception/GlobalExceptionHandler.java
> +/* Exception Handling for Validations
Please remove commented code

2022-11-22 13:02 UTC, vikaramm requested changes

2022-11-22 13:02 UTC, vikaramm commented on src/main/java/com/billingapi/controller/InvoiceController.java
> +    static Logger logger = LogManager.getLogger(InvoiceController.class);
Can we use @Slf4j. and please explore more about this and implement in a proper way.

2022-11-22 13:24 UTC, vikaramm requested changes

2022-11-22 13:24 UTC, vikaramm commented on src/main/java/com/billingapi/exception/GlobalExceptionHandler.java
> +@ControllerAdvice
use @RestControllerAdvice

2022-11-25 06:24 UTC, vikaramm requested changes

2022-11-25 06:24 UTC, vikaramm commented on src/main/java/com/billingapi/service/InvoiceServiceImpl.java
>          BigDecimal newtax = new BigDecimal(tax);
We don't need to create unnecessary objects.

2022-11-25 06:24 UTC, vikaramm commented on src/main/java/com/billingapi/service/InvoiceServiceImpl.java
>          BigDecimal newSum = (sum = price.add(newtax).add(newvat)).subtract(newdiscount).subtract(newdiscountonsale);
BigDecimal total = (price.add(BigDecimal .valueOf(newtax).add(igDecimal .valueOfnewvat)).subtract(igDecimal .valueOfnewdiscount).subtract(igDecimal .valueOfnewdiscountonsale);

2022-11-25 06:24 UTC, vikaramm commented on src/main/java/com/billingapi/controller/InvoiceController.java
> +
delete unnecessary spaces

2022-11-25 06:24 UTC, vikaramm commented on src/main/java/com/billingapi/controller/InvoiceController.java
>          Invoice invoice = invoiceService.findInvoiceById(invoiceId);
throws InvoiceNotFoundException -> why we need here ?

2022-11-25 06:24 UTC, vikaramm commented on src/main/java/com/billingapi/controller/InvoiceController.java
> +
@Valid - wd don't need here

2022-11-25 06:24 UTC, vikaramm commented on src/main/java/com/billingapi/controller/request/InvoiceRequest.java
>      private double tax;
tax , vat and discount should be in percentage and @Digit(integer=2, fraction=2)

2022-11-25 06:24 UTC, vikaramm commented on src/main/java/com/billingapi/controller/request/InvoiceRequest.java
> +    @Max(value = 1000   )
@Max(value=99999999)

2022-11-25 06:24 UTC, vikaramm commented on src/main/java/com/billingapi/exception/GlobalExceptionHandler.java
>      protected ResponseEntity<Object> handleHttpRequestMethodNotSupported(HttpRequestMethodNotSupportedException ex, HttpHeaders headers, HttpStatus status, WebRequest request) {
why we nedd here ?

2022-11-25 06:24 UTC, vikaramm commented on src/main/java/com/billingapi/exception/GlobalExceptionHandler.java
> +
we shouldn't override ...

2022-11-25 06:24 UTC, vikaramm commented on src/main/java/com/billingapi/service/InvoiceServiceImpl.java
> +        if (invoice.isDeleted()) equals(false);
if (!invoice.isDeleted()) {

}

2022-11-25 06:24 UTC, vikaramm commented on src/main/java/com/billingapi/exception/GlobalExceptionHandler.java
>      protected ResponseEntity<Object> handleHttpRequestMethodNotSupported(HttpRequestMethodNotSupportedException ex, HttpHeaders headers, HttpStatus status, WebRequest request) {
handle these exception : HttpRequestMethodNotSupportedException , MethodArgumentTypeMismatchException, BindException, HttpMessageNotReadableException, HttpMessageNotReadableException,

2022-11-29 04:44 UTC, vikaramm approved these changes

2022-11-29 04:44 UTC, vikaramm commented on pom.xml
> +        <dependency>
lobok repeated

2022-11-29 04:44 UTC, vikaramm commented on src/main/java/com/billingapi/exception/ExceptionResponse.java
> +    private String message;
change it to List<String> message;

2022-11-29 04:44 UTC, vikaramm commented on src/main/java/com/billingapi/exception/ErrorModelResponse.java
> +public class ErrorModelResponse {
Delete this class , no required anymore

2022-11-29 04:44 UTC, vikaramm commented on src/main/java/com/billingapi/exception/GlobalExceptionHandler.java
> +        for (FieldError fieldError : ex.getBindingResult().getFieldErrors()) {
change the code here to -> ex.hasFieldErrors()?ex.getFieldErrors().stream().map(error -> error.isBindingFailure() ?
"Invalid value "+ error.getRejectedValue() " for field" + error.getField()
: 
"The field " + fieldError.getField() + "  has  " + fieldError.getDefaultMessage()))

2022-11-29 04:44 UTC, vikaramm commented on src/main/java/com/billingapi/service/InvoiceServiceImpl.java
> +        {
code not formatted

2022-11-29 04:44 UTC, vikaramm commented on src/main/java/com/billingapi/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<Object> handleConstraintValidationException(
check if it is not required delete it.

2022-11-29 04:44 UTC, vikaramm commented on src/main/java/com/billingapi/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<Object> handleConstraintValidationException(
check if it is not required delete it.

2022-11-29 06:55 UTC, merged