Unit testing
suchidp/BillingApiAssignment pull request #5
Opened 2022-12-08 06:16 UTC by suchidp

2022-12-13 04:57 UTC, vmahto requested changes

2022-12-13 04:57 UTC, vmahto commented on src/test/java/com/billingapi/controller/InvoiceControllerTest.java
> +        response.andDo(print()).
do we need print() here ?

2022-12-13 04:57 UTC, vmahto commented on src/test/java/com/billingapi/controller/InvoiceControllerTest.java
> +                .build();
Move Invoice build related code inside a method.

2022-12-13 04:57 UTC, vmahto commented on src/test/java/com/billingapi/controller/InvoiceControllerTest.java
> +        ResultActions response = mockMvc.perform(get("/invoice/aa", invoiceId));
declare a variable for url e.g. INVALID_INVOICE_ID_URL = "/invoice/aa" . To make the code more readble

2022-12-13 04:57 UTC, vmahto commented on src/test/java/com/billingapi/controller/InvoiceControllerTest.java
> +    /*  Test to Create invoice if Method arguments is not valid   then it throws exception  MethodArgumentTypeMismatch
make the commment more decriptive.

2022-12-13 04:57 UTC, vmahto commented on src/test/java/com/billingapi/controller/InvoiceControllerTest.java
> +                           .contentType(MediaType.APPLICATION_JSON).content(objectMapper.writeValueAsString(invoiceResponse)))
the req body should have invoiceRequest obj

2022-12-13 04:57 UTC, vmahto commented on src/test/java/com/billingapi/controller/InvoiceControllerTest.java
> +           invoiceRequest.setTotal(alltotal);
We don't need to write to much code here. This can be conb=verted to single line.
subtotal calculation , we need to discuss ?

2022-12-13 04:57 UTC, vmahto commented on src/test/java/com/billingapi/controller/InvoiceControllerTest.java
> +
You can use parameterized test & MethodSource annotation , because similar test are repetative.

2022-12-26 09:43 UTC, vikaramm requested changes

2022-12-26 09:43 UTC, vikaramm commented on src/test/java/com/billingapi/controller/InvoiceControllerTest.java
> +    public void givenListOfInvoices_whenGetAllInvoice_thenReturnInvoiceList() throws Exception {
always start test method name with test keyword.
e.g. testGetInvoicesShouldReturnListOfInvoices()

2022-12-26 09:43 UTC, vikaramm commented on src/test/java/com/billingapi/controller/InvoiceControllerTest.java
> +                .andDo(print())
remove print()

2022-12-26 09:43 UTC, vikaramm commented on src/test/java/com/billingapi/controller/InvoiceControllerTest.java
> +    @Test
expected = NotFoundException.class

2022-12-26 09:43 UTC, vikaramm commented on src/test/java/com/billingapi/controller/InvoiceControllerTest.java
> +    public void givenInvoice_whenfindInvoiceById_thenReturnfindById() throws Exception {
method name ?

2022-12-26 09:43 UTC, vikaramm commented on src/test/java/com/billingapi/controller/InvoiceControllerTest.java
> +    public void should_throw_exception_whenCreateInvoice_ifQuantityIsGreaterThan99999999OrZero_thenReturnaddInvoiceFailed(Integer quantity) throws Exception {
method name

2022-12-26 09:43 UTC, vikaramm commented on src/test/java/com/billingapi/controller/InvoiceControllerTest.java
> +    public void should_throw_exception_whenCreateInvoice_ifDiscountIsGreaterThan99_thenReturnaddInvoiceFailed(double discount) throws Exception {
Bad Request all negative scebario should be tested using Parameterised test.

2022-12-26 11:17 UTC, vikaramm approved these changes
looks good

2022-12-26 11:26 UTC, merged